apiVersion: v1
kind: Pod
metadata:
  name: skaffold
  labels:
    app: skaffold
spec:
  containers:
  - name: skaffold-demo
    image: viraj/skaffold-demo
---
apiVersion: v1
kind: Service
metadata:
  name: skaffold
spec:
  selector:
    app: skaffold
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
